side = "corp"
excludes = ["megaprix_qualifier", "storgotic_resonator"]
rares = [
    "drago_ivanov",
    "seamless_launch",
    "gold_farmer",
    "wage_workers",
    "engram_flush",
    "tributary",
    "dr_vientiane_keeling",
    "nanisivik_grid",
    "anoetic_void",
    "the_holo_man",
    "end_of_the_line",
    "manegarm_skunkworks",
    "touch_ups",
    "cayambe_grid",
    "oppo_research",
    "nanomanagement",
    "drafter",
    "tatu_bola",
    "phat_gioan_baotixita",
    "gaslight",
    "bran_1_0",
    "tranquility_home_grid",
    "fully_operational",
    "charlotte_cacador",
    "saisentan",
    "tucana",
    "measured_response",
    "your_digital_life",
    "mutually_assured_destruction",
    "cohort_guidance_program",
    "red_level_clearance",
    "afshar",
    "ansel_1_0",
    "federal_fundraising",
    "petty_cash",
    "reaper_function",
    "anemone",
    "big_deal",
    "moon_pool",
    "regolith_mining_license",
]
